### ISSUE TITLE
Filter shows meals that do not have an explicit diet

### ISSUE THREAD

**Issue by LukasPietzschmann** [Tanikai/uniulm_mensa_frontend#6]
![Screenshot_20240731_110749](https://github.com/user-attachments/assets/c476d710-a597-40ba-8991-bd615c7ac354)

I think the salad and desert 😉 should not be shown.

**Comment by LukasPietzschmann** [comment]
Fun fact: when I run the site locally, this issue isn't present.
My local deployment uses commit 9647622

**Comment by Tanikai** [comment]
It's not present in your deployment, as you have to use commit 9678a2ae268a2b060a995f99b84ffadaa7f737e0.

I thought that it would be better when meals without a meal type are shown in all filters. We could change it so that they are only shown in "unrestricted".

**Comment by LukasPietzschmann** [comment]
OMG I for sure though I did a `git pull` and that 9647622 was the HEAD commit.

I think showing a meal that has no diet set, when I specifically filtered for meals that adhere to it, is kinda weird. But ultimately you decide :)
